import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import { Product, Sale, Expense } from './database';

interface PDFExportOptions {
  title: string;
  fileName: string;
  content: string;
}

export const generatePDFContent = (html: string): string => {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <style>
        body {
          font-family: Arial, sans-serif;
          margin: 20px;
          color: #333;
        }
        h1 {
          color: #0a7ea4;
          border-bottom: 2px solid #0a7ea4;
          padding-bottom: 10px;
        }
        h2 {
          color: #0a7ea4;
          margin-top: 20px;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin: 15px 0;
        }
        th, td {
          border: 1px solid #ddd;
          padding: 10px;
          text-align: left;
        }
        th {
          background-color: #0a7ea4;
          color: white;
        }
        tr:nth-child(even) {
          background-color: #f9f9f9;
        }
        .summary {
          background-color: #f0f0f0;
          padding: 15px;
          border-radius: 5px;
          margin: 15px 0;
        }
        .metric {
          display: inline-block;
          width: 48%;
          margin: 5px 1%;
          padding: 10px;
          background-color: white;
          border: 1px solid #ddd;
          border-radius: 5px;
        }
        .footer {
          margin-top: 30px;
          padding-top: 10px;
          border-top: 1px solid #ddd;
          font-size: 12px;
          color: #666;
        }
      </style>
    </head>
    <body>
      ${html}
      <div class="footer">
        <p>Generated by Business Manager Pro - ${new Date().toLocaleString()}</p>
        <p>This is an offline-generated report. All data is stored locally on your device.</p>
      </div>
    </body>
    </html>
  `;
};

export const exportReportToPDF = async (
  title: string,
  metrics: Record<string, string | number>,
  currency: string
): Promise<void> => {
  try {
    const metricsHTML = Object.entries(metrics)
      .map(([key, value]) => `<div class="metric"><strong>${key}:</strong> ${value}</div>`)
      .join('');

    const html = `
      <h1>${title}</h1>
      <div class="summary">
        ${metricsHTML}
      </div>
    `;

    const pdfContent = generatePDFContent(html);
    const fileName = `report-${new Date().toISOString().split('T')[0]}.html`;
    const filePath = `${FileSystem.cacheDirectory}${fileName}`;

    await FileSystem.writeAsStringAsync(filePath, pdfContent);

    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(filePath, {
        mimeType: 'text/html',
        dialogTitle: `Share ${title}`,
      });
    } else {
      console.log('File saved to:', filePath);
    }
  } catch (error) {
    console.error('Error exporting report:', error);
    throw error;
  }
};

export const exportInventoryToPDF = async (products: Product[], currency: string): Promise<void> => {
  try {
    const tableRows = products
      .map(
        (p) => `
        <tr>
          <td>${p.name}</td>
          <td>${p.barcode || 'N/A'}</td>
          <td>${p.quantity}</td>
          <td>${currency}${p.sellingPrice.toFixed(2)}</td>
          <td>${currency}${(p.quantity * p.sellingPrice).toFixed(2)}</td>
        </tr>
      `
      )
      .join('');

    const totalValue = products.reduce((sum, p) => sum + p.quantity * p.sellingPrice, 0);

    const html = `
      <h1>Inventory Report</h1>
      <p>Generated: ${new Date().toLocaleString()}</p>
      <h2>Current Inventory</h2>
      <table>
        <thead>
          <tr>
            <th>Product Name</th>
            <th>Barcode</th>
            <th>Quantity</th>
            <th>Unit Price</th>
            <th>Total Value</th>
          </tr>
        </thead>
        <tbody>
          ${tableRows}
        </tbody>
      </table>
      <div class="summary">
        <div class="metric"><strong>Total Items:</strong> ${products.length}</div>
        <div class="metric"><strong>Total Units:</strong> ${products.reduce((sum, p) => sum + p.quantity, 0)}</div>
        <div class="metric"><strong>Inventory Value:</strong> ${currency}${totalValue.toFixed(2)}</div>
      </div>
    `;

    const pdfContent = generatePDFContent(html);
    const fileName = `inventory-${new Date().toISOString().split('T')[0]}.html`;
    const filePath = `${FileSystem.cacheDirectory}${fileName}`;

    await FileSystem.writeAsStringAsync(filePath, pdfContent);

    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(filePath, {
        mimeType: 'text/html',
        dialogTitle: 'Share Inventory Report',
      });
    }
  } catch (error) {
    console.error('Error exporting inventory:', error);
    throw error;
  }
};

export const exportSalesHistoryToPDF = async (
  sales: Sale[],
  currency: string,
  startDate?: Date,
  endDate?: Date
): Promise<void> => {
  try {
    const filteredSales = sales.filter((sale) => {
      const saleDate = new Date(sale.createdAt);
      if (startDate && saleDate < startDate) return false;
      if (endDate && saleDate > endDate) return false;
      return true;
    });

    const tableRows = filteredSales
      .map(
        (sale) => `
        <tr>
          <td>${new Date(sale.createdAt).toLocaleString()}</td>
          <td>${currency}${sale.total.toFixed(2)}</td>
          <td>${currency}${sale.discount.toFixed(2)}</td>
          <td>${currency}${sale.tax.toFixed(2)}</td>
          <td>${sale.paymentMethod}</td>
        </tr>
      `
      )
      .join('');

    const totalRevenue = filteredSales.reduce((sum, s) => sum + s.total, 0);
    const totalDiscount = filteredSales.reduce((sum, s) => sum + s.discount, 0);
    const totalTax = filteredSales.reduce((sum, s) => sum + s.tax, 0);

    const html = `
      <h1>Sales History Report</h1>
      <p>Period: ${startDate?.toLocaleDateString() || 'All'} to ${endDate?.toLocaleDateString() || 'All'}</p>
      <h2>Sales Transactions</h2>
      <table>
        <thead>
          <tr>
            <th>Date & Time</th>
            <th>Amount</th>
            <th>Discount</th>
            <th>Tax</th>
            <th>Payment Method</th>
          </tr>
        </thead>
        <tbody>
          ${tableRows}
        </tbody>
      </table>
      <div class="summary">
        <div class="metric"><strong>Total Transactions:</strong> ${filteredSales.length}</div>
        <div class="metric"><strong>Total Revenue:</strong> ${currency}${totalRevenue.toFixed(2)}</div>
        <div class="metric"><strong>Total Discount:</strong> ${currency}${totalDiscount.toFixed(2)}</div>
        <div class="metric"><strong>Total Tax:</strong> ${currency}${totalTax.toFixed(2)}</div>
      </div>
    `;

    const pdfContent = generatePDFContent(html);
    const fileName = `sales-history-${new Date().toISOString().split('T')[0]}.html`;
    const filePath = `${FileSystem.cacheDirectory}${fileName}`;

    await FileSystem.writeAsStringAsync(filePath, pdfContent);

    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(filePath, {
        mimeType: 'text/html',
        dialogTitle: 'Share Sales History Report',
      });
    }
  } catch (error) {
    console.error('Error exporting sales history:', error);
    throw error;
  }
};
